# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias desktop='cd ~/Desktop'
alias downloads='cd ~/Downloads'
alias documents='cd ~/Documents'
alias code='cd ~/Code'

# Shortcuts
alias compress='tar -zcvf'
alias extract='tar -zxvf'
alias install='sudo apt install'
alias v='vim'
alias s='sudo'
alias px='ps aux'
alias fn='find -name'
alias p='ping 8.8.8.8'
alias fs='stat -f "%z bytes"'
alias fn='find ./ -name'
alias myip='curl ip.appspot.com'
alias mysqlc='mysql -u root -p'
alias mysqldumpc='mysqldump -u root -p'

# Defaults
alias rm='rm -v'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# GIT
alias g='git'
alias ga='git add'
alias gap='git add -p'
alias gd='git diff'
alias gds='git diff --staged'
alias glp='git log -p'
alias gc='git commit -m'
alias gs='git status -s'
alias gp='git push origin master'
alias gl='git log --graph --abbrev-commit --pretty=oneline -n 20'
alias master='git checkout master'
alias dev='git checkout dev'
alias commit='git commit'
alias checkout='git checkout'
alias fetch='git fetch -p'
alias pull='git pull --rebase --prune --verbose --no-ff --no-commit --no-stat'
alias push='git push origin HEAD'
alias forcepush='git push --force-with-lease origin HEAD'
alias undopush='git push -f origin HEAD^:master'
alias stash='git stash'
alias pop='git stash pop'
alias undo='git reset HEAD^'
alias amend='git commit --amend --no-edit'
alias log='git log --graph --abbrev-commit --pretty=oneline -n 20'

# PHP
alias art='php artisan'
alias pdoc='/usr/bin/phpdoc -d ./ -t ./docs -i "docs/*,vendor/*"'
alias pdbg='/usr/bin/php -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=127.0.0.1 -dxdebug.collect_vars=1 -dxdebug.show_local_vars=1 -dxdebug.remote_connect_back=1 -dxdebug.remote_autostart=1 -dxdebug.remote_idekey=DBGKEY'
