if status is-interactive
    alias `~`='cd ~'
    touch /Users/ahmad/.hushlogin
end

#fish_add_path /usr/local/bin/

set -gx GPG_TTY (tty)

abbr -a 'addremote' 'git remote add'
abbr -a 'allmerged' 'git branch --merged -r | grep -v "\*"'
abbr -a 'amend' 'git commit --amend --no-edit'
abbr -a 'amende' 'git commit --amend'
abbr -a 'autorebase' 'git rebase -i --autosquash --autostash'
abbr -a 'back' 'git checkout -'
abbr -a 'branch' 'git branch'
abbr -a 'branches' 'git branch -a'
abbr -a 'browse' 'hub browse'
abbr -a 'checkout' 'git checkout'
abbr -a 'clone' 'git clone'
abbr -a 'co' 'git checkout'
abbr -a 'codes' 'cd ~/projects'
abbr -a 'commit' 'git commit'
abbr -a 'commits' 'hub browse -- commits'
abbr -a 'compress' 'tar -zcvf'
abbr -a 'copy' 'fpp -c "echo \$F | pbcopy"'
abbr -a 'd' 'docker'
abbr -a 'deleted' 'git log --diff-filter=D --summary | grep delete'
abbr -a 'desktop' 'cd ~/Desktop'
abbr -a 'documents' 'cd ~/Documents'
abbr -a 'dotfiles' 'cd /Users/ahmadsamiei/projects/dotfiles'
abbr -a 'downloads' 'cd ~/Downloads'
abbr -a 'edit' 'fpp -c subl'
abbr -a 'extract' 'tar -zxvf'
abbr -a 'fetch' 'git fetch -p'
abbr -a 'fetchall' 'git fetch -all'
abbr -a 'fixup' 'git commit --fixup'
abbr -a 'fn' 'find ./ -name'
abbr -a 'forcepush' 'git push --force-with-lease origin HEAD'
abbr -a 'fs' 'stat -f "%z bytes"'
abbr -a 'g' 'git'
abbr -a 'ga' 'git add'
abbr -a 'gap' 'git add -p'
abbr -a 'gc' 'git commit -m'
abbr -a 'gd' 'git diff'
abbr -a 'gds' 'git diff --staged'
abbr -a 'gl' 'git log --graph --decorate --abbrev-commit --pretty=format:"%C(auto,yellow)%h%Creset %C(auto,bold)%s%Creset %Cgreen(%ar)%Creset%Cred%d%Creset %C(auto,dim)%aN%Creset" -n 20'
abbr -a 'glf' 'git log -- '
abbr -a 'glp' 'git log -p'
abbr -a 'gp' 'git push origin master'
abbr -a 'gs' 'git status -s'
abbr -a 'hmm' 'subl ./'
abbr -a 'install' 'sudo apt install'
abbr -a 'issues' 'hub browse -- issues'
abbr -a 'k' 'kubectl'
abbr -a 'l' 'ls -CF'
abbr -a 'la' 'ls -A'
abbr -a 'll' 'ls -alF'
abbr -a 'log' 'git log -p --decorate'
abbr -a 'develop' 'git checkout develop'
abbr -a 'main' 'git checkout main'
abbr -a 'master' 'git checkout master'
abbr -a 'merge' 'git merge'
abbr -a 'merged' 'git branch --merged | grep -v "\*"'
abbr -a 'mergenoff' 'git merge --no-ff'
abbr -a 'myip' 'curl ip.appspot.com'
abbr -a 'mysqlc' 'mysql -u root -p'
abbr -a 'mysqldumpc' 'mysqldump -u root -p'
abbr -a 'mystandup' 'standup --author=(git config user.name)'
abbr -a 'new' 'git checkout -b'
abbr -a 'newfiles' 'git whatchanged --diff-filter=A'
abbr -a 'news' 'git log ..master'
abbr -a 'notmerged' 'git branch --no-merged'
abbr -a 'p' 'ping 8.8.8.8'
abbr -a 'po' 'git fetch -p origin; git pull --rebase --prune --verbose --no-ff --no-commit --no-stat --autostash origin master'
abbr -a 'pop' 'git stash pop'
abbr -a 'projects' 'cd ~/projects'
abbr -a 'prune' 'git remote prune origin'
abbr -a 'ptree' 'tree -d -L 10 -I "vendor|tests|test|node_modules" --matchdirs:q'
abbr -a 'pull' 'request=hub pull-request'
abbr -a 'pullme' 'git fetch -p upstream; git pull --rebase --prune --verbose --no-ff --no-commit --no-stat --autostash upstream master'
abbr -a 'pullorigin' 'git fetch -p origin; git pull --rebase --prune --verbose --no-ff --no-commit --no-stat --autostash origin master'
abbr -a 'pullrequest' 'hub pull-request'
abbr -a 'push' 'git push origin HEAD'
abbr -a 'px' 'ps aux'
abbr -a 'r' 'rigfor'
abbr -a 're' 'rigfor pusher-elements'
abbr -a 'rebase' 'git rebase --autostash'
abbr -a 'rebaseme' 'git rebase master --autostash'
abbr -a 'remotes' 'git remote -v'
abbr -a 'repo' "open https://github.(git config remote.origin.url | cut -f2 -d. | tr ':' /)"
abbr -a 'revert' 'git revert'
abbr -a 'rm' 'rm -v'
abbr -a 'rmbranch' 'git branch -D'
abbr -a 'rmibranch' 'git push origin :'
abbr -a 'rmmerged' 'git branch --merged | grep -v "\*" | xargs -n 1 git branch -D'
abbr -a 'rp' 'rigfor pusherinos'
abbr -a 's' 'sudo'
abbr -a 'show' 'git show'
abbr -a 'standup' 'git --no-pager log --all --no-merges --oneline --date="relative" --since="yesterday"'
abbr -a 'stash' 'git stash -k -u'
abbr -a 'stashall' 'git stash --include-untracked'
abbr -a 'ta' 'terraform apply'
abbr -a 'td' 'terraform destroy'
abbr -a 'tf' 'terraform validate; terraform fmt'
abbr -a 'ti' 'terraform init'
abbr -a 'tmp' 'cd /tmp'
abbr -a 'tp' 'terraform plan'
abbr -a 'tv' 'terraform validate'
abbr -a 'undo' 'git reset --soft HEAD^'
abbr -a 'undopush' 'git push -f origin HEAD^:master'
abbr -a 'unstage' 'git reset HEAD'
abbr -a 'unstageall' 'git reset HEAD .'
abbr -a 'v' 'vim'
abbr -a 'wiki' 'hub browse -- wiki'
abbr -a 'wip' 'git commit -m "WIP"'
abbr -a 'work' 'cd /Users/ahmadsamiei/projects/pusher/'
abbr -a '..' 'cd ..'
abbr -a '...' 'cd ../..'
abbr -a '....' 'cd ../../..'
abbr -a '.....' 'cd ../../../..'
abbr -a 'kx' 'kubectx'
abbr -a 'kn' 'kubens'
abbr -a 'k' 'kubectl'
abbr -a 'pods' 'kubectl get pods'
abbr -a 'nest' '~/projects/nest/'
abbr -a 'pusher' '~/projects/pusher/'
